
CREATE TABLE Products
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
ImgProduct NVARCHAR(MAX) NOT NULL,
NameProduct NVARCHAR(MAX) NOT NULL,
DescriptionProduct NVARCHAR(MAX) NOT NULL,
CountProduct INT NOT NULL,
CategoryId INT FOREIGN KEY REFERENCES Categories(Id) NOT NULL,

)